playBGM('abovedeck')
setBG('trans')
enterNVL()
enter('shawn', 'c')
enter('cy', 'a')
enter('leo', 'e')
speak('ari', "...")
speak('leo', "...Never play that on board my ship again.")
speak('cy', "Return to the Sea...")
speak('leo', "Do you hear me Shawn? Never. Play. That. On. My. Ship. Again.")
speak('shawn', "Oh? I thought we were all equals. Who died and made you captain?")
exit('cy')
enter('ari', 'a')
speak('ari', "Dangerous words, Shawn. Why don't you take a cue from our mute guest and sew your lips shut? Or shall I do it for you?")
speak('leo', "I'm going back to the bridge. This is over.")
exit('leo')
clear()
speak('ari', "It'll be a long night.")
exit('ari')
speak('shawn', "Haha, what is it? Was I that out of tune?")
enter('cy', 'a')
speak('cy', "Kid, come on. I'll show you to your cabin.")
exitNVL()

playBGM('belowdeck')
targetTele('YourCabin', 'warp')
setSwitch('begin_night_1', true)
setSwitch('enable_inventory', true)
