setBG('hallway')
playBGM('crew')

enterNVL()
enter('shawn', 'b')
speak('shawn', "Well, what do you think?")
enter('you', 'd')
speak('you', "...")
speak('shawn', "Do you like the interior design? It's mostly my project, you know. Have you ever heard of the SS Andrea Dorea?")
speak('you', "...?")
speak('shawn', "Really? It's like the second most famous shipwreck of all time. But you have to have heard of the Titanic, right? They were both ocean liners, straight out of another world. Ships were luxury back then!")
speak('shawn', "If you were a rich dude, you had a stateroom on one of these babies. It was prestige! Status! And these boats were fab, decked out, art deco romantic, not like those ugly yachts.")
speak('shawn', "But the Andrea Dorea, the Titantic... One day the Revolution too, will be resting on the bottom of the ocean. And when a ship is on the ocean floor, its crew, that's when their souls come back to join the living.")
clear()
speak('shawn', "I figure, if I were a dude from 1956 who died on a posh ocean liner, I'd come haunt someplace that looked like my old digs. Right? It'd feel like home! So I want the Revolution to feel as home-ly as possibly to all those fifties ghosts out there.")
speak('you', "...")
speak('shawn', "Oh don't give me that look, kiddo. When it's me going down with the ship, I'll come back and join some other crew as their ghost engineer. I'll be helpful! I'll make a pretty cool ghost I think.")
speak('shawn', "And I think I feel them... lost souls. Think they'd feel welcome here? If you train your third eye... They wander these halls too.")
speak('you', "...")
clear()
speak('shawn', "Ahhh well who cares about that. Did I introduce myself? Probably not. But the name's Shawn. I'm the heart and soul of the Revolution even if no one else will admit it. Now what do they call you, kiddo?")
speak('you', "...")
speak('shawn', "Got it. Although Awkward Silence is a bit long for a name. Just calling you Silence would be pretty cool though. Yeah?")
speak('you', "...")
speak('shawn', "Sounds good, Silence! Anyway, here's the radio room. Want to go visit Ari?")
exitNVL()

wait(1.0)
play('day1_05')
