setBG('radioroom')
enterNVL()
enter('ari', 'c')
speak('ari', "...and that, I believe, is the chief takeaway from the events of the past three years. Not all revolutions must be secular. Not all left-wing movements must be pure. Class must unite us. All other divisions must fall. Revolution, out.")
clear()
enter('shawn', 'a')
enter('you', 'e')
speak('shawn', "Hey hey Ari! Me and Silence were touring the place, figured we'd drop in.")
speak('ari', "You and... who?")
speak('shawn', "Silence! The kid! That's their name.")
speak('you', "...")
speak('ari', "That's not anyone's name, Shawn. Stop clowning around and get out of here. You're not scheduled to broadcast until 02:00.")
clear()
speak('shawn', "C'mon, Ari. Give me an earlier slot some time. I'd have more fans.")
speak('ari', "No you wouldn't. No one listens to Revolution Radio to hear your guitar interpretations or schizophrenic rambling.")
speak('shawn', "Rude. Your show's pretty boring too.")
speak('ari', "I don't kid myself. People tune into Revolution Radio for commerical-free top 40 EDM, not my commentary. Pirate radio is dead. Maybe some of today's idiot youth will stick around and listen to what I have to say about the state of today's politics, but it'll be one percent of our listeners.")
speak('shawn', "Hey if I only connect to the souls of one percent of my audience, I'd be stoked.")
speak('ari', "One percent of your listeners would round down to zero.")
clear()
speak('shawn', "Hey hey hey, don't trash talk me in front of Silence.")
speak('ari', "Oh. I forgot you were there.")
speak('you', "...")
speak('ari', "I'm Ari. No last name.")
speak('shawn', "You can call her Comrade Ari. She's our cook, and deck officer too. She runs Revolution Radio out of the onboard station. Oh, and she's a veteran -- I'm pretty sure she's been sailing since the original Andrea Dorea.")
clear()
speak('ari', "The Andrea Dorea wrecked in the 50's, and anyone who adopted a nom de guerre with 'comrade' in it got killed by the CIA in the 70's. Stop making shit up, Shawn, and don't come back down here until it's your broadcast slot.")
speak('shawn', "Love you too, Ari.")
speak('ari', "And to you, kid... This lousy world of ours isn't any place for children, and this boat even less so. My sincerest wish that you get out of here as soon as possible and that we see each other never again.")
exitNVL()

wait(1.0)
play('day1_06.lua')