setBG('black')

enterNVL()
speak('leo', "Ha HA! Home free! Can't catch the Revolution.")
setBG('sunset')
enter('leo', 'e')
speak('leo', "Not too bad, eh?")
enter('shawn', 'b')
speak('shawn', "The speed of Hermes, the stealth of Hecate, and the blessings of Poseidon.")
enter('ari', 'a')
speak('ari', "The only casualty was my dignity. I'm not doing accents again. It'll be radio silence.")
enter('cy', 'c')
speak('cy', "We've had closer calls.")
speak('shawn', "And of course we should thank our good luck charm.")
exit('cy')
exit('shawn')
exit('leo')
exit('ari')
enter('you', 'c')
speak('you', "...")
enter('cy', 'a')
speak('cy', "A person can't be a good luck charm.")
enter('shawn', 'e')
speak('shawn', "Then our little friend here is at minimum a good omen.")
exit('cy')
enter('ari', 'a')
speak('ari', "You mean a bad omen. If we hadn't stopped to pick them up, we wouldn't have wound up a hairsbreadth away from discovery.")
exit('shawn')
enter('leo', 'e')
speak('leo', "Either way, it's been too long since all of us were even awake at the same time, so let's take the opportunity to share a meal.")
clear()
exit('ari')
enter('shawn', 'a')
speak('shawn', "That's it! A welcoming party for our guest. Let's drink under the stars. And sing. Sing! I'll bring my guitar.")
speak('leo', "Any objections?")
exit('shawn')
enter('ari', 'a')
speak('ari', "As long as our 'guest' is only a guest until port. And they stay in their quarters.")
speak('leo', "Lighten up a bit Ari. We'll meet up in the usual spot in an hour. Until then, Cy, can you handle the instruments? I need to pay a visit to the cargo fridge in bay 12.")
speak('ari', "I'll be needed on the broadcast, but... If you want to share a meal, I'll be there. I might even cook something.")
exit('ari')
enter('shawn', 'a')
speak('shawn', "Then I'll give our guest a tour. And we'll find you a proper cabin. It's been ages since any of us have seen another soul aboard here, so that makes you the guest of honor.")
speak('leo', "Yes. Welcome aboard the Revolution.")
wait(0.5)
speak('you', "...")
exitNVL()

play('day1_04')
