setBG('engine')
playBGM('belowdeck')
enterNVL()

enter('shawn', 'c')
speak('shawn', "And this... Welcome to Chateu de Shawn!")
speak('you', "...")
speak('shawn', "Aw, don't give me that face. I don't really live here. This is the engine room of the Revolution. From right to left here, we have Inky, Pinky, Blinky, and Clyde. Inky is the worst of them. I need to lubricate him every day and whenever we have propulsion troubles, I always come to Inky first.")
clear()
speak('shawn', "You ever done a piston reconditioning, Silent? How about a refit on the high seas?")
speak('you', "...")
speak('shawn', "That's what I thought! And even so, you'd probably be better at it than Cy or Ari or even Leo. To be a good engineer, you need to know your engines on a spiritual level. Are you chakras in sync, Silence?")
speak('you', "...?")
speak('shawn', "Are you extingent energy levels in tune with the aura of the entities around you?")
speak('you', "...???")
speak('shawn', "Then you'll never be an engineer. Sorry to say, you've either got the gift of engineering or you don't. Blessing and a curse, all that.")
clear()
speak('shawn', "But Inky looks like he's behaving tonight, even if I need to make repairs on Blinky when we're in port. It's a good diesel-electric setup we've got so even if we're moving at 5 knots to evade detection then we can keep full power on - ")
speak('shawn', "Ahhh never mind. I don't want to bore you. Besides, it should be about time for the victory feast anyway, right? Let's head up to the main deck.")
exitNVL()

wait(0.5)
play('day1_08')