setBG('infirmary')

enterNVL()
enter('you', 'c')
speak('you', "...")
speak('cy', "You're awake!")
exit('you')
enter('cy', 'd')
enter('you', 'b')
speak('you', "...")
speak('cy', "Um, well. Hello. You're aboard the Revolution. We found you floating and unconscious a few hours ago. Everything will be alright.")
speak('cy', "I'm Cynthia. You can call me Cy if you like.")
speak('you', "...")
speak('cy', "You got a name there, kiddo?")
speak('you', "...")
speak('cy', "Don't worry. You're safe here now, no matter what happened out there.")
speak('you', "...")
speak('cy', "Haa... Well, I imagine you've been through a hell of a time. You don't have to talk until you're ready.")
clear()

enter('shawn', 'e')
speak('shawn', "Cyyy! Listen up! Cy! Cy, we have company on the way!")
exit('you')
enter('you', 'b')
enter('ari', 'c')
speak('ari', "Cy. Bridge. Now. Leo needs you upstairs.")
speak('cy', "Right away.")
speak('ari', "Wait. They're awake.")
speak('shawn', "Well hey nice to meet you, little guy. What brings you to our corner of the seven seas?")
speak('ari', "Shawn, shut up. Cy, bridge.")
exit('cy')
exit('shawn')
exit('ari')
exit('you')
enter('you', 'b')
speak('you', "...")
enter('ari', 'e')
speak('ari', "Wait. No way I'm leaving you alone down here. Follow me and keep your mouth shut.")
exitNVL()

wait(2.0)
play('day1_02')
