setBG('engine')
playBGM('belowdeck')
enterNVL()
enter('cy', 'b')
enter('you', 'd')
wait(2)
speak('cy', "Ah... I have no idea how to repair this. If we have to put to port to fix this, Leo will be furious...")
speak('cy', "I'm sorry about this, Kid. Leo's temper is something else whenever Cooper comes up. Leo is a coward about that. Or maybe we all are...")
speak('you', "...")
speak('cy', "I probably be shouldn't be talking to you about this, but... I can't do it Leo's way, just denying anything ever happened and threatening anyone who steps on his toes. I wonder... with Shawn missing, could Leo have...?")
clear()
speak('cy', "Once you're ashore you'll figure out the truth soon enough. I don't think it's right to keep this hidden any longer, but Cooper was the old captain, back when we were the Maersk Fredensborg, not the Revolution.")
speak('cy', "Someone murdered him on the bridge, here, on the ship. He wasn't a good man, and his death opened up new roads for everyone aboard, but, to go like that... His soul can't be happy. And since that night, neither can mine. Shawn always said he sensed ghosts, but I never have. The dead are just gone. That's why death is scary.")
speak('cy', "Well, who am I to lecture you? You've been closer to death than any of us.")
speak('you', "...")
exitNVL()
wait(1)

play('day2_04')
