setBG('bridge')
playBGM('abovedeck')

enterNVL()
enter('leo', 'b')
enter('ari', 'a')
speak('ari', "It's not looking great.")
speak('leo', "We'll hold our course.")
enter('cy', 'd')
enter('you', 'e')
speak('cy', "Sorry if I'm late, Leo. I can take over now.")
speak('leo', "There might not be a chance to rest. Check this out.")
speak('cy', "What is that on the radar?")
speak('ari', "In all my years I've never seen anything like it before.")
speak('leo', "Lord God almighty. Lord guard me, Lord give me strength...")
speak('ari', "It must be a storm. Because it sure isn't a ship. Don't let it get to your head.")
clear()
speak('cy', "If that's a storm, its intensity must be huge to appear like that on radar... And appearing out of nothing... Could this be related to the broadcast about Cooper?")
speak('leo', "Not that name!")
speak('ari', "There's no power in a name. But yes, Cy, shut up about that around the kid.")
speak('cy', "It doesn't matter. The kid knows who he is. Was.")
speak('ari', "You told them? Exactly how much?")
speak('cy', "Nothing. But that the captain was murdered is being broadcast at full strength on every frequency right now. There's no use trying to hide it.")
speak('leo', "But - ")
speak('leo', "Dammit. Never mind. We need to focus on this storm, or whatever it is.")
exitNVL()

setSwitch('begin_night_2', true)
playBGM('retribution')
targetTele('Decky', 'warp')
setSwitch('enable_inventory', true)
