setBG('radioroom')
playBGM('morse')
enterNVL()
enter('leo', 'a')
enter('cy', 'b')
enter('ari', 'd')
slowtype(4)
speak("????", "THINE SOULS ART FORFEIT")
speak("????", "MUTINEERS ART DAMNED")
speak("????", "MARE DEO SHALL RETURN THEE UNTO THE SEA")
speak("????", "RETRIBUTION IS AT HAND")
slowtype(60)
playBGM('retribution')
wait(4)
clear()
speak('leo', "Lord God almighty. Lord guard me, Lord give me strength... This can only mean one thing.")
speak('ari', "Don't get carried away.")
speak('leo', "It heard us. IT heard us. One of you spoke! Which one of you? I told all of you to never mention Mare Deo, that song, or that... act... ever again! But now it heard us. We're dead men sailing.")
speak('ari', "Don't be like this, Leo. Mare Deo isn't real. Sailors have believed in thousands of curses and legends but not a single one of them has turned out true. What century do you sail in, man?")
speak('leo', "What other explanation could there be?")
speak('ari', "Shawn sold us out and is trying to scare us.")
speak('cy', "Or he's just trying to scare us. It'd be like him to pull a prank like this.")