setBG('radioroom')
playBGM('morse')
targetTele('Black', 'target')
enterNVL()
enter('leo', 'a')
enter('cy', 'b')
enter('ari', 'd')
speak('ari', "Listen.")
wait(1)
exitNVL();
playBGM('retribution')
beginMessage()
message("RETRIBUTION IS AT HAND")
wait(2)
message("THINE SOULS ART FORFEIT")
wait(2)
message("FOR THE MURDER OF COOPER NEILSEN")
wait(2)
message("MARE DEO SHALL RETURN THEE UNTO THE SEA")
wait(2)
message("RETRIBUTION IS AT HAND")
wait(3)
endMessage()
wait(1)
enterNVL()
enter('leo', 'a')
enter('cy', 'b')
enter('ari', 'd')
speak('ari', "...and it repeats.")
speak('leo', "Lord God almighty. Lord guard me, Lord give me strength... This can only mean one thing.")
speak('ari', "Don't get carried away.")
speak('leo', "It heard us. IT heard us. One of you spoke! Which one of you? I told all of you to never mention Mare Deo, that song, or that... act... ever again! But now it heard us. We're dead men sailing.")
speak('ari', "Don't be like this, Leo. Mare Deo isn't real. Sailors have believed in thousands of curses and legends but not a single one of them has turned out true. What century do you sail in, man?")
speak('leo', "What other explanation could there be?")
clear()
speak('ari', "It would be mighty difficult to overpower our own signal without a real deal broadcasting tower like ours. I would guess someone here has hijacked our equipment and is playing this on repeat. In other words, Shawn sold us out and is trying to scare us.")
speak('cy', "Sold us out to whom? It's a prank, isn't it? It would be like him.")
speak('ari', "I've known that erstwhile idiot since he was as young as the kid here, and this isn't in Shawn's nature. It's malicious.")
speak('leo', "But this means someone, one of us three or Shawn, is broadcasting out that... name...")
speak('cy', "Cooper Nielsen...")
speak('leo', "Don't say it!")
speak('ari', "Keep rational.")
clear()
speak('cy', "The murder of Cooper Nielsen. But the only ones who know that secret...")
speak('ari', "The three of us, and Shawn. And the kid, now that you've blabbed it.")
speak('leo', "Don't! You can't say these things aloud. That's the whole point -- the sea must keep its secrets.")
speak('ari', "You're a coward at the feet of superstition, Leo. Keep rational.")
speak('ari', "One of us, or somehow the missing Shawn, hijacked our broadcast equipment. Their goal in the short term is to scare us with this business about the ex-captain. If they plan on blackmail, then we'll find out shortly. That's the rational explanation.")
speak('ari', "As for which of us is the traitor... I'll just say I doubt it's Shawn.")
speak('leo', "Okay, this is under control then. Whoever sabotaged our radio equipment is human. For now I don't care who it is. Ari, catch some sleep while you can. I'll cover the bridge. Cy, check the engines. We'll pull through this.")
exit('ari')
exit('cy')
clear()
speak('leo', "And you...")
enter('you', 'e')
speak('you', "...")
speak('leo', "You just stay out of the way.")
exitNVL()

play('day2_03')
