enterNVL()
enter('you', 'C')
speak('you', "This is YOU speaking.")
exit('you')
enter('you', 'B')
speak('you', "Now I'm over here!")
enter('shawn', 'D')
wipe()
speak('shawn', "Hello I'm shawn")
enter('ari', 'E')
speak('ari', "I'm ari!")
speak('you', "and I.. Am... YOU!")
wipe()
speak('shawn', 'seeya!')
exit('shawn')
exit('ari')
exit('you')
enter('you', 'C')
speak('you', "Now I'm all alone again...")
speak('????', "Here is some narration!")
speak('????', "You can consider this an extended internal monologue meant to extend for more than one line in order to ensure that linebreaks are still working properly because there's a good chance something screwed them up.")
speak('you', "Seems to have worked?")
speak('you', "Anyway someone go find a better font, this is literally the VT nokia garbage")
exitNVL()