setNextScript('sketch/3_11', false)
setNextScript('partner/3_12', false, 1)
setNews('day3')
setSwitch('day3/post_elle', true)
setSwitch('day1', true)
setSwitch('day2', true)
setSwitch('day3', true)
setSwitch('control/2_10', true)
setSwitch('nighttime', false)
teleport('Apartment/Bedroom', 'start')
setSwitch('partner/2_14', true)
setSwitch('control/2_11', true)
setSwitch('sis/1_contact', true)
setSwitch('y_1_02', true)