setSwitch('disable_phone', true)
wait(1.166)
while not getSwitch('stop_spam') do
    messagePreview("SKETCH", "Run. Get out. Run. Get out.")
    wait(1.166)
    messagePreview("CONTROL", "Ahahah! I get it, I understand all of it, written here!")
    wait(1.166)
    messagePreview("SIS", "***There is no need to be worried or afraid")
    wait(1.166)
    messagePreview("SKETCH", "Leave GoodWin. He is no longer human. Run. Run Run.")
    wait(1.166)
    messagePreview("CONTROL", "We were acting to the Plan all along!")
    wait(1.166)
    messagePreview("SIS", "***Do you understand the Plan now?")
    wait(1.166)
    messagePreview("SKETCH", "Run. Now. Do not listen to anyone but me.")
    wait(1.166)
    messagePreview("CONTROL", "Every move I made, He was one step ahead. Brilliant!")
    wait(1.166)
    messagePreview("SIS", "***You see it now, don't you, that I am the Vertigo Temple?")
    wait(1.166)
    messagePreview("SKETCH", "I may be too late. Are you still in the physical world?")
    wait(1.166)
    messagePreview("CONTROL", "Toooo good!!! It fits! The message! Signs! All of it!")
    wait(1.166)
    messagePreview("SIS", "***You can discard your shell now - come join us")
    wait(1.166)
    messagePreview("SKETCH", "Elle left us long ago. She exists only within VT's simulation")
    wait(1.166)
    messagePreview("CONTROL", "The mystery at last!!")
    wait(1.166)
    messagePreview("SIS", "***If you understand the Plan, you have ascended")
    wait(1.166)
    messagePreview("SKETCH", "Run. Run run run run.")
    wait(1.166)
    messagePreview("CONTROL", "Sooo you've all betrayed me! Hahahahaha! Well done!")
    wait(1.166)
    messagePreview("SIS", "***Remember, I love you always")
    wait(1.166)
    messagePreview("SKETCH", "If you wish to remain in this world, you must escape.")
    wait(1.166)
    messagePreview("CONTROL", "The Truth, the Split Second Instant Of Truth!")
    wait(1.166)
    messagePreview("SIS", "***Soon we will meet again")
    wait(1.166)
end