setBG('trans')
enterNVL()
speak('????', 'Maersk Fredensborg manifest')
speak('????', 'Cooper Neilsen - Ship master')
speak('????', 'Leonardo Ghisolfi - Chief officer')
speak('????', 'Cynthia Pelkey - Deck officer')
speak('????', 'Shawn Hughes - Chief engineer')
speak('????', 'Ari Ari - Second engineer')
speak('????', '-------------------')
speak('????', 'Irina Stalev - Passenger')
speak('????', 'Georgi Stalev - Passenger')
exitNVL()
