setBG('trans')
enterNVL()
enter('ari', 'b')
enter('shawn', 'd')
speak('shawn', "Ari, you're locking up for the night?")
speak('ari', "You're not going to broadcasting, if that's what you're asking.")
speak('shawn', "But I'm scheduled, aren't I? Are you still upset Ari? I didn't get under your skin did I?")
speak('ari', "No. I don't believe in any of that nonsense, about the song, that legend. But you know how Leo is. If you're doing this to intentionally annoy him, I have nothing to say to you.")
clear()
speak('ari', "But someone's on our wavelength. It's out of my hands.")
speak('shawn', "Well that's rude.")
speak('ari', "Signal intrusion. It's just noise. I'm not sure if someone's trying to shut us down, or it's the weather, or something else. All the other channels are noisy too.")
speak('shawn', "Ohh, I think I know why.")
speak('ari', "Not another word.")
walk('ari', 4, 'WEST')
speak('shawn', "Haha...")
walk('shawn', 7, 'WEST')
exitNVL()
setSwitch('night1_hall', true)
