setSwitch('night1_conclusion02', true)
setBG('night')
enterNVL()
enter('shawn', 'c')
speak('shawn', "Hahaha, what's up, Silence? You're looking a little pale.")
speak('shawn', "Well don't worry. I've got it all figured out now. I was wondering when someone like you would show up, because I've been waiting so long. It's not a whole lot of fun always looking over your shoulder, now is it, Silence? We'll all be ghosts in the end anyway.")
speak('shawn', "It's like... If fate is inevitable, then what's the point of dragging it out? And Leo can deny as much as he wants but this fate.")
speak('shawn', "So, hey, the mystery's finally solved. I know what I need to do now. Seeya!!")
exit('shawn')
clear()
fadeOutBGM(1)
wait(1.0)
playSFX('cannonball')
wait(1.5)
setBG('black')
wait(3)
playSFX('chaser2')
wait(4.5)

play('day2_00')
