setBG('trans')
enterNVL()
enter('leo', 'b')
enter('cy', 'd')
speak('leo', "...so just ignore Shawn. He's not the problem. The problem is the dead guy.")
speak('cy', "I don't see how.")
speak('leo', "He didn't die naturally.")
speak('cy', "I could've told you that.")
speak('leo', "No, I mean, he didn't drown.")
clear()
speak('leo', "He was stabbed to death. That we found him in the water...")
speak('cy', "It couldn't have been the kid. Not in a million years.")
speak('leo', "I think it's more a question of 'what' did it than 'who,' but, either way, something really, really bad happened out there. Maybe someone's after Kid. Maybe Kid's caught up in something. Point is, we might be in for a rough time.")
speak('cy', "Especially if Shawn has decided that this is a sign from Mare - ")
speak('leo', "Come on Cy. I was clear. Never mention that.")
clear()
speak('cy', "I think you might be paranoid.")
speak('leo', "No. I know what I'm talking about. There are no sins at sea unless you confess them.")
speak('cy', "I wish it were that simple...")
wait(1.5)
clear()
enter('you', 'e')
speak('leo', "Kid! How long have you been there?")
speak('cy', "Having trouble sleeping?")
speak('you', "...")
speak('cy', "I've found stargazing helps. Even from the porthole. But you can do that from your cabin, right?")
speak('leo', "Lock their door this time or something.")
exitNVL()

targetTele('YourCabin', 'warp')
playBGM('belowdeck')
setSwitch('night1_bridge', true)
