setBG('trans')
enterNVL()
enter('ari', 'b')
enter('shawn', 'd')
speak('shawn', "Ari, you're locking up for the night?")
speak('ari', "You're not going to be broadcasting, if that's what you're asking.")
speak('shawn', "But I'm scheduled, aren't I? Are you still upset Ari? I didn't get under your skin did I?")
speak('ari', "No. I don't believe in any of that nonsense, about the song, that legend. But you know how Leo is. If you're doing this to intentionally annoy him, I have nothing to say to you.")
clear()
speak('shawn', "Aww, come on. You and I go way back. Don't hold a grudge.")
speak('ari', "It doesn't matter what I think or not. Fact is, someone's on our wavelength. Even if we transmit, no one would pick up our signal.")
speak('shawn', "Well that's rude of them.")
speak('ari', "Signal intrusion. It seems to only be heavy noise on our frequency right now. I'm not sure if someone's trying to shut us down, or it's the weather, or something else. All the other channels are noisy too.")
speak('shawn', "Ohh, I think I know why.")
speak('ari', "Not another word.")
walk('ari', 4, 'WEST')
speak('shawn', "Haha...")
walk('shawn', 7, 'WEST')
exitNVL()
setSwitch('night1_hall', true)
