playBGM('retribution')

walk('leo2', 1, 'EAST')
wait(0.6)

setBG('trans')
enterNVL()
enter('leo', 'b')
enter('ari', 'd')
speak('ari', "Don't get any closer, Leo.")
speak('leo', "Then drop the knife, Ari!")
speak('ari', "I'm no fool.")
speak('leo', "You're a murderer! Mutineer! Mare Deo, take her, not me! I've done nothing!")
exitNVL()

wait(0.5)
walk('ari2', 1, 'EAST')
wait(0.3)
face('ari2', 'WEST')

enterNVL()
enter('leo', 'b')
enter('ari', 'd')
speak('ari', "Maybe you were right all along. Mare Deo is here for us all. You and me and Shawn and Cy. Everyone had a hand in it, and so we'll all pay.")
speak('leo', "No! Never! O Sailors, keep your secrets!")
speak('ari', "Ahaha, you idiot, Leo. Mare Deo will take you either way, and every deed will catch up with you in the end. The point of the song is that those that confess will have their souls redeemed.")
speak('ari', "We're both going to die here, whether to a storm or a seamonster I don't know, but on my way out, I'll have a clean conscience. How about you?")
speak('leo', "If the ocean ever finds the haul... If... If...")
exitNVL()

wait(0.5)
walk('leo2', 1, 'WEST')
wait(1.0)
enterNVL()
enter('leo', 'b')
enter('ari', 'd')
speak('leo', "You! Kid!")
speak('ari', "Then who are you, Kid? Psh. I suppose I already knew.")
speak('leo', "No! Mare Deo! Kid, your traitor! You betrayed us to Mare -")
exitNVL()

walk('ari2', 3, 'WEST')
wait(1)
playSFX('stab')
enterNVL()
enter('leo', 'b')
speak('leo', "Grrrk...")
speak('ari', "Sorry about the knife in the back, but I can't have you hurting the kid.")
speak('ari', "And you're wrong, anyway. Mare Deo is the sea, not the kid.")
enter('ari', 'c')
clear()
wait(1)
speak('ari', "Now I'm ready, Confessor. I'll pay the price and die with a smile on my face.")
fadeOutBGM(2)
exitNVL()

dim()
wait(1.5)
playBGM('brownian')
wait(1.5)
beginMessage()
message("YOUR TASK IS COMPLETE, MY SERVANT")
wait(2)
message("RETURN TO THE SEA")
wait(2)
endMessage()

enterNVL()
enter('you', 'c')
speak('you', "...")
exitNVL()
shanty2()
