fadeOutBGM(1)
setBG('trans')
setSwitch('enable_inventory', false)

enterNVL()
enter('cy', 'c')
speak('cy', "Oh, it's you.")
playBGM('abovedeck')
setSwitch('night2_cy', true)
wait(2)
speak('cy', "You're here just in time. The storm's arrived.")
exitNVL()
cyPan()
await()
enterNVL()
speak('cy', "There's not much hope, is there? Shawn was the only real engineer. There's been some damage already, and with a crew this small... But I don't think that's really a storm out there. Maybe Ari's right, or Leo's lying, but I think Shawn somehow knew that Mare Deo was on the way.")
speak('cy', "He knew the legend best. It's almost a funny story -- a sea monster without the ability to touch anything above the surface of the sea. It's a monster that's supposed to seek out and punish sinners. Mutineers, mostly. An avenging monster.")
speak('cy', "I think Leo believes that so long as he never admits to the deed, the beast can't touch him. Ari doesn't believe it exists. I didn't before. But now...")
clear()
speak('cy', "Let me tell you a story. Four crewmen aboard a cargo ship. The Maersk Fredensborg. Their captain was a vicious man who ran half a dozen illegal business under the table. One of those crewmen he paid off, one believed in the cause, one he offered haven from those that were after her, and one never had any morals to begin with so long as he was allowed his hobbies.")
speak('cy', "The captain offered passage to two refugees, mother and child. It was routine, except that at the other end of the journey, the plan was to turn them over to their pursuers. All of those four crewman had something to gain and nothing to lose. So the Maersk Fredensborg became the Revolution, in the name of those two refugees.")
speak('cy', "Every murderer feels justified. They have to, or every time they see the reflections of the stars in the water, the eyes of the dead will stare back.")
clear()
speak('cy', "So tell me. Was I justified? I took one life to save two.")
speak('cy', "And now that I've confessed my sins, O Confiteor Deo, wilt thou deign to spare my soul?")
exitNVL()
fadeOutBGM(3)
wait(3)
playSFX('cannonball')
wait(2)
cyEat()
await()
setSwitch('night2_chaser', true)
spawnChaser('chaser_spawn', 1.5)