fadeOutBGM(.5)
playBGM('lights_off')
awaitBGMLoad()
wait(5.2)
setSwitch('lights_off', true)
wait(.1)
setSwitch('lights_off', false)
wait(.1)
setSwitch('lights_off', true)
wait(.1)
setSwitch('lights_off', false)
wait(.1)
setSwitch('lights_off', true)
wait(3)

face('hero', 'SOUTH')
setSwitch('flashlight', true)
setNextScript('control/3_32')
