fadeOutBGM(.5)
setSwitch('lights_off', true)
wait(.1)
setSwitch('lights_off', false)
wait(.1)
setSwitch('lights_off', true)
wait(.1)
setSwitch('lights_off', false)
playBGM('lights_off')
awaitBGMLoad()
wait(5.2)
setSwitch('lights_off', true)
wait(.1)
setSwitch('lights_off', false)
wait(.1)
setSwitch('lights_off', true)
wait(.1)
setSwitch('lights_off', false)
wait(.1)
setSwitch('lights_off', true)
wait(3)

setSwitch('flashlight', true)
setNextScript('control/3_32')

setNextScript('y!sms/3_05', false, 24)
setNextScript('partner/3_33', false, 30)

setSpeedMult(0.6)
